# Assignment Day 3


Q.1) Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
import numpy as np 
arr = np.arange(2,51,3) # creating numpy array 
print(arr)


[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


Q.2) Accept two lists of 5 elements each from the user.Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [4]:
import numpy as np
arr1,arr2 = (list(map(int,input().split())) for i in range(2))
nmpy_arr1 = np.array(arr1) 
nmpy_arr2 = np.array(arr2)
print(np.concatenate((nmpy_arr1,nmpy_arr2)))  #Concatenation of arrays
print(np.sort(np.concatenate((nmpy_arr1,nmpy_arr2)))) #Sorting of arrays


3 7 11 67 4
5 9 33 8 2
[ 3  7 11 67  4  5  9 33  8  2]
[ 2  3  4  5  7  8  9 11 33 67]


Q.3) Write a code snippet to find the dimensions of a ndarray and its size.

In [7]:
arr = np.array([ [11,33,77,99] , [5,3,1,6] , [12,76,45,32] ])
print(arr.shape) #dimenion of array
print(arr.size) #size of array


(3, 4)
12


Q.4) How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims


In [11]:
arr = np.array([ [33,77,55,34,65,21,54,90,67,52,85,44] ])

print(arr,arr.shape) 

arr = arr.reshape(3,4) 

print(arr,arr.shape)


[[33 77 55 34 65 21 54 90 67 52 85 44]] (1, 12)
[[33 77 55 34]
 [65 21 54 90]
 [67 52 85 44]] (3, 4)


Q.5) Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [3]:
import numpy as np
arr1 = np.array([ [44,77] , [33,88] , [32,79] ])
arr2 = np.array([ [54,89] , [45,74] , [23,11] ])
print(np.vstack((arr1,arr2))) # Vertical Stack
print(np.hstack((arr1,arr2))) # Horizontal Stack


[[44 77]
 [33 88]
 [32 79]
 [54 89]
 [45 74]
 [23 11]]
[[44 77 54 89]
 [33 88 45 74]
 [32 79 23 11]]


Q.6) How to get unique items and counts of unique items?

In [5]:
lst = [33,77,44,67,99,44,33,65,99,32]
lst = list(set(lst))
print(lst)
print(len(lst)) #count of unique items


[32, 33, 65, 99, 67, 44, 77]
7
